verify-token:
  handler: src/handlers/VerifyToken.verify

listDocuments:
  handler: src/handlers/documents/list.handler
  events:
    - http: 
        path: /documents
        method: get
        
getDocument:
  handler: src/handlers/documents/get.handler
  events:
    - http: 
        path: /document/{id}
        method: get
        
addDocument:
  handler: src/handlers/documents/add.handler
  events:
    - http: 
        path: /document
        method: post
        
updateDocument:
  handler: src/handlers/documents/update.handler
  events:
    - http: 
        path: /document/{id}
        method: put
        
deleteDocument:
  handler: src/handlers/documents/delete.handler
  events:
    - http: 
        path: /document/{id}
        method: delete
        
signup:
  handler: src/handlers/users/signup.handler
  events:
    - http: post /signup
login:
  handler: src/handlers/users/login.handler
  events:
    - http: post /login